FROM node:22-alpine AS base
WORKDIR /app

COPY package*.json ./
COPY apps/api/package*.json ./apps/api/

RUN npm install

COPY apps/api ./apps/api

WORKDIR /app/apps/api
RUN npx prisma generate

EXPOSE 3001
CMD ["node", "src/server.js"]
